#! /bin/bash

# exit when any command fails
set -e

current=`pwd`

echo "===== Compilation de $1 =====" >&2
echo >&2
cp $1 /tmp/
cd /tmp/
gnatmake -I${current}/IncludeGada -I${current}/IncludeExosS2 $1 -o /tmp/exe

echo
echo
echo "===== Exécution de $1 ====="
echo
/tmp/exe 2>&1

