package body Caracteres is

   -- Raccourcis pour faciliter l'écriture
   E : T_Pixel := Eteint ;
   A : T_Pixel := Allume ;

   procedure Init is
   begin

      Table := (
              1 => (Car => ' ',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

              2 => (Car => '!',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

              3 => (Car => '#',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,E,A,E,E),
                    (E,A,E,A,E,E),
                    (A,A,A,A,A,E),
                    (E,A,E,A,E,E),
                    (A,A,A,A,A,E),
                    (E,A,E,A,E,E),
                    (E,A,E,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

              4 => (Car => '$',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,A,A,A,E),
                    (A,E,A,E,E,E),
                    (A,E,A,E,E,E),
                    (E,A,A,A,E,E),
                    (E,E,A,E,A,E),
                    (E,E,A,E,A,E),
                    (A,A,A,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

              5 => (Car => '%',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,E,E,A,E),
                    (A,E,A,E,A,E),
                    (E,A,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,A,E,E),
                    (A,E,A,E,A,E),
                    (A,E,E,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

              6 => (Car => ''',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

              7 => (Car => '(',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,E,E,E))),

              8 => (Car => ')',
          Trame => ((E,E,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,E,E,E),
                    (E,E,E,E,E,E))),

              9 => (Car => '*',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (A,E,A,E,A,E),
                    (E,A,A,A,E,E),
                    (A,E,A,E,A,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             10 => (Car => '+',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             11 => (Car => ',',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,A,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,E,E,E),
                    (E,E,E,E,E,E))),

             12 => (Car => '-',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             13 => (Car => '.',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,A,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E))),

             14 => (Car => '/',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,A,E),
                    (E,E,E,E,A,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             15 => (Car => '0',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             16 => (Car => '1',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,A,E,E,E),
                    (A,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             17 => (Car => '2',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,A,E),
                    (E,E,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             18 => (Car => '3',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,E,A,E),
                    (E,E,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,A,E),
                    (E,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             19 => (Car => '4',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,A,A,E,E),
                    (E,A,E,A,E,E),
                    (E,A,E,A,E,E),
                    (A,E,E,A,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             20 => (Car => '5',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,A,A,E,E),
                    (A,A,E,E,A,E),
                    (E,E,E,E,A,E),
                    (E,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             21 => (Car => '6',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             22 => (Car => '7',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,E,A,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             23 => (Car => '8',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             24 => (Car => '9',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,A,E),
                    (E,E,E,E,A,E),
                    (E,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             25 => (Car => ':',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,A,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,A,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E))),

             26 => (Car => ';',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,A,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,A,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,E,E,E),
                    (E,E,E,E,E,E))),

             27 => (Car => '=',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             28 => (Car => '?',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,A,E),
                    (E,E,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             29 => (Car => '@',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,A,A,E),
                    (A,E,A,E,A,E),
                    (A,E,A,E,A,E),
                    (A,E,A,A,E,E),
                    (A,E,E,E,E,E),
                    (E,A,A,A,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             30 => (Car => 'A',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,A,A,A,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             31 => (Car => 'B',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,E,E),
                    (E,A,E,E,A,E),
                    (E,A,E,E,A,E),
                    (E,A,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,A,E,E,A,E),
                    (E,A,E,E,A,E),
                    (E,A,E,E,A,E),
                    (A,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             32 => (Car => 'C',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             33 => (Car => 'D',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,E,E),
                    (E,A,E,E,A,E),
                    (E,A,E,E,A,E),
                    (E,A,E,E,A,E),
                    (E,A,E,E,A,E),
                    (E,A,E,E,A,E),
                    (E,A,E,E,A,E),
                    (E,A,E,E,A,E),
                    (A,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             34 => (Car => 'E',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,A,A,A,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             35 => (Car => 'F',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,A,A,A,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             36 => (Car => 'G',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,A,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             37 => (Car => 'H',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,A,A,A,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             38 => (Car => 'I',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             39 => (Car => 'J',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,A,A,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (A,E,E,A,E,E),
                    (E,A,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             40 => (Car => 'K',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,A,E,E),
                    (A,E,A,E,E,E),
                    (A,A,E,E,E,E),
                    (A,E,A,E,E,E),
                    (A,E,E,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             41 => (Car => 'L',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             42 => (Car => 'M',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,A,E,A,A,E),
                    (A,E,A,E,A,E),
                    (A,E,A,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             43 => (Car => 'N',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (A,A,E,E,A,E),
                    (A,A,E,E,A,E),
                    (A,E,A,E,A,E),
                    (A,E,A,E,A,E),
                    (A,E,E,A,A,E),
                    (A,E,E,A,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             44 => (Car => 'O',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             45 => (Car => 'P',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,A,A,A,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             46 => (Car => 'Q',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,A,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,A,E),
                    (E,E,E,E,E,E))),

             47 => (Car => 'R',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,A,A,A,E,E),
                    (A,E,A,E,E,E),
                    (A,E,E,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             48 => (Car => 'S',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,A,E),
                    (E,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             49 => (Car => 'T',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             50 => (Car => 'U',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             51 => (Car => 'V',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,E,A,E,E),
                    (E,A,E,A,E,E),
                    (E,A,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             52 => (Car => 'W',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,A,E,A,E),
                    (A,E,A,E,A,E),
                    (A,E,A,E,A,E),
                    (A,E,A,E,A,E),
                    (E,A,E,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             53 => (Car => 'X',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,E,A,E,E),
                    (E,A,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,A,E,E),
                    (E,A,E,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             54 => (Car => 'Y',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,E,A,E,E),
                    (E,A,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             55 => (Car => 'Z',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,E,A,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             56 => (Car => '[',
          Trame => ((E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E))),

             57 => (Car => '\',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,E,A,E),
                    (E,E,E,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             58 => (Car => ']',
          Trame => ((E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E))),

             59 => (Car => '^',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,A,E,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             60 => (Car => '_',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,E,E,E))),

             61 => (Car => '`',
          Trame => ((E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             62 => (Car => 'a',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,A,E),
                    (E,A,A,A,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,A,A,E),
                    (E,A,A,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             63 => (Car => 'b',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             64 => (Car => 'c',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             65 => (Car => 'd',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,A,E),
                    (E,E,E,E,A,E),
                    (E,E,E,E,A,E),
                    (E,A,A,A,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             66 => (Car => 'e',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,A,A,A,A,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             67 => (Car => 'f',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,A,E,E),
                    (E,A,E,E,A,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (A,A,A,A,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             68 => (Car => 'g',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,A,E),
                    (E,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E))),

             69 => (Car => 'h',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,A,A,E,E),
                    (A,A,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             70 => (Car => 'i',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             71 => (Car => 'j',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (E,E,E,A,E,E),
                    (A,E,E,A,E,E),
                    (A,E,E,A,E,E),
                    (E,A,A,E,E,E))),

             72 => (Car => 'k',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,A,E,E),
                    (A,E,A,E,E,E),
                    (A,A,E,E,E,E),
                    (A,E,A,E,E,E),
                    (A,E,E,A,E,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             73 => (Car => 'l',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             74 => (Car => 'm',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,E,A,E,E),
                    (A,E,A,E,A,E),
                    (A,E,A,E,A,E),
                    (A,E,A,E,A,E),
                    (A,E,A,E,A,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             75 => (Car => 'n',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,A,A,E,E),
                    (A,A,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             76 => (Car => 'o',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             77 => (Car => 'p',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,A,A,A,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E))),

             78 => (Car => 'q',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,A,E),
                    (E,E,E,E,A,E),
                    (E,E,E,E,A,E),
                    (E,E,E,E,A,E))),

             79 => (Car => 'r',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,A,A,E,E),
                    (A,A,E,E,A,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             80 => (Car => 's',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,A,A,E,E),
                    (A,E,E,E,A,E),
                    (E,A,A,E,E,E),
                    (E,E,E,A,E,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             81 => (Car => 't',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (A,A,A,A,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,E,E),
                    (E,A,E,E,A,E),
                    (E,E,A,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             82 => (Car => 'u',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,A,A,E),
                    (E,A,A,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             83 => (Car => 'v',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,E,A,E,E),
                    (E,A,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             84 => (Car => 'w',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,A,E,A,E),
                    (A,E,A,E,A,E),
                    (A,E,A,E,A,E),
                    (E,A,E,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             85 => (Car => 'x',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (E,A,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,A,E,E),
                    (A,E,E,E,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             86 => (Car => 'y',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (A,E,E,A,A,E),
                    (E,A,A,E,A,E),
                    (E,E,E,E,A,E),
                    (A,E,E,E,A,E),
                    (E,A,A,A,E,E))),

             87 => (Car => 'z',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,A,E,E),
                    (E,E,A,E,E,E),
                    (E,A,E,E,E,E),
                    (A,E,E,E,E,E),
                    (A,A,A,A,A,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             88 => (Car => '{',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,A,A,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (A,A,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,A,A,E),
                    (E,E,E,E,E,E))),

             89 => (Car => '|',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E))),

             90 => (Car => '}',
          Trame => ((E,E,E,E,E,E),
                    (A,A,E,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,E,A,A,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (E,E,A,E,E,E),
                    (A,A,E,E,E,E),
                    (E,E,E,E,E,E))),

             91 => (Car => '~',
          Trame => ((E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,A,E,E,A,E),
                    (A,E,A,E,A,E),
                    (A,E,E,A,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E),
                    (E,E,E,E,E,E)))) ;

   end Init ;

  begin
     Init ;
end Caracteres ;

