package body Tennis is

   Les_Joueurs : T_Classement(1..100) :=
     ( 
       ("Novak Djokovic        ", "SRB",   0),
       ("Andy Murray           ", "GBR",   0),
       ("Roger Federer         ", "SUI",   0),
       ("David Ferrer          ", "ESP",   1),
       ("Rafael Nadal          ", "ESP",  -1),
       ("Tomas Berdych         ", "CZE",   0),
       ("Jo-Wilfried Tsonga    ", "FRA",   1),
       ("Juan Martin Del Potro ", "ARG",  -1),
       ("Richard Gasquet       ", "FRA",   0),
       ("Stanislas Wawrinka    ", "SUI",   0),
       ("Tommy Haas            ", "GER",   3),
       ("Marin Cilic           ", "CRO",  -1),
       ("Kei Nishikori         ", "JPN",   2),
       ("Janko Tipsarevic      ", "SRB",  -2),
       ("Milos Raonic          ", "CAN",   1),
       ("Nicolas Almagro       ", "ESP",  -3),
       ("Gilles Simon          ", "FRA",   1),
       ("Philipp Kohlschreiber ", "GER",   1),
       ("Sam Querrey           ", "USA",   1),
       ("Juan Monaco           ", "ARG",  -3),
       ("John Isner            ", "USA",   0),
       ("Jerzy Janowicz        ", "POL",   1),
       ("Kevin Anderson        ", "RSA",   2),
       ("Alexandr Dolgopolov   ", "UKR",   0),
       ("Benoit Paire          ", "FRA",   1),
       ("Andreas Seppi         ", "ITA",  -4),
       ("Jeremy Chardy         ", "FRA",   0),
       ("Grigor Dimitrov       ", "BUL",   0),
       ("Mikhail Youzhny       ", "RUS",   2),
       ("Tommy Robredo         ", "ESP",   4),
       ("Fabio Fognini         ", "ITA",  -2),
       ("Julien Benneteau      ", "FRA",   0),
       ("Florian Mayer         ", "GER",  -3),
       ("Lukas Rosol           ", "CZE",   2),
       ("Martin Klizan         ", "SVK",   0),
       ("Jurgen Melzer         ", "AUT",   1),
       ("Jarkko Nieminen       ", "FIN",   1),
       ("Ernests Gulbis        ", "LAT",   2),
       ("Feliciano Lopez       ", "ESP",   4),
       ("Marcos Baghdatis      ", "CYP",  -1),
       ("Marcel Granollers     ", "ESP",  -8),
       ("Nikolay Davydenko     ", "RUS",   6),
       ("Mardy Fish            ", "USA",  -2),
       ("Viktor Troicki        ", "SRB",  13),
       ("Denis Istomin         ", "UZB",  -3),
       ("Radek Stepanek        ", "CZE",   6),
       ("Thomaz Bellucci       ", "BRA",  -3),
       ("Albert Montanes       ", "ESP",  -1),
       ("Victor Hanescu        ", "ROU",   5),
       ("Daniel Gimeno-Traver  ", "ESP",  -1),
       ("Grega Zemlja          ", "SLO",  -1),
       ("Pablo Andujar         ", "ESP",  -7),
       ("Horacio Zeballos      ", "ARG",  -7),
       ("Ivan Dodig            ", "CRO",  -3),
       ("Michael Llodra        ", "FRA",   0),
       ("Xavier Malisse        ", "BEL",   0),
       ("Daniel Brands         ", "GER",   2),
       ("Robin Haase           ", "NED",   8),
       ("Fernando Verdasco     ", "ESP",  -6),
       ("Igor Sijsling         ", "NED",   2),
       ("Albert Ramos          ", "ESP",   3),
       ("Roberto Bautista-Agut ", "ESP",   6),
       ("Bernard Tomic         ", "AUS",  -2),
       ("Dmitry Tursunov       ", "RUS",  -4),
       ("Marinko Matosevic     ", "AUS",  -2),
       ("Edouard Roger-Vasselin", "FRA",  -1),
       ("Gael Monfils          ", "FRA",  14),
       ("Tobias Kamke          ", "GER",   4),
       ("Richard Berankis      ", "LTU",  -2),
       ("Yen-Hsun Lu           ", "TPE",   6),
       ("Paolo Lorenzi         ", "ITA",  -1),
       ("Carlos Berlocq        ", "ARG",  -1),
       ("Evgeny Donskoy        ", "RUS",   9),
       ("Alejandro Falla       ", "COL",   0),
       ("Guido Pella           ", "ARG",   8),
       ("Lukas Lacko           ", "SVK",   1),
       ("Andrey Kuznetsov      ", "RUS",  -2),
       ("Aljaz Bedene          ", "SLO",   2),
       ("Guillermo Garcia-Lopez", "ESP",   0),
       ("Paul-Henri Mathieu    ", "FRA", -11),
       ("Alex Jr. Bogomolov    ", "RUS",   4),
       ("Lleyton Hewitt        ", "AUS",   4),
       ("Ryan Harrison         ", "USA",   9),
       ("David Goffin          ", "BEL", -26),
       ("Leonardo Mayer        ", "ARG", -12),
       ("Kenny de Schepper     ", "FRA",   5),
       ("Simone Bolelli        ", "ITA",   1),
       ("Dudi Sela             ", "ISR",   1),
       ("Gilles Muller         ", "LUX",  -5),
       ("Rajeev Ram            ", "USA",   3),
       ("Thiemo de Bakker      ", "NED",   4),
       ("Jan Hajek             ", "CZE",  -5),
       ("Guillaume Rufin       ", "FRA",   5),
       ("James Blake           ", "USA",   2),
       ("Santiago Giraldo      ", "COL", -17),
       ("Adrian Ungur          ", "ROU",  10),
       ("Michael Russell       ", "USA",   2),
       ("Philipp Petzschner    ", "GER",   4),
       ("Vasek Pospisil        ", "CAN",   4),
       ("Rogerio Dutra Da Silva", "BRA",  -6) ) ;
   
   
   Les_Joueuses : T_Classement(1..100) :=  
     ( ("Serena Williams       ", "USA", 0),
       ("Victoria Azarenka     ", "BLR",   1),
       ("Maria Sharapova       ", "RUS",  -1),
       ("Agnieszka Radwanska   ", "POL",   0),
       ("Sara Errani           ", "ITA",   0),
       ("Na Li                 ", "CHN",   0),
       ("Angelique Kerber      ", "GER",   1),
       ("Petra Kvitova         ", "CZE",  -1),
       ("Caroline Wozniacki    ", "DEN",   1),
       ("Maria Kirilenko       ", "RUS",   2),
       ("Roberta Vinci         ", "ITA",   4),
       ("Ana Ivanovic          ", "SRB",   2),
       ("Nadezda Petrova       ", "RUS",  -2),
       ("Samantha Stosur       ", "AUS",  -5),
       ("Marion Bartoli        ", "FRA",  -2),
       ("Jelena Jankovic       ", "SRB",   2),
       ("Sloane Stephens       ", "USA",   0),
       ("Dominika Cibulkova    ", "SVK",  -2),
       ("Carla Suarez Navarro  ", "ESP",   1),
       ("Kirsten Flipkens      ", "BEL",   1),
       ("Pavlyuchenkova        ", "RUS",  -2),
       ("Ekaterina Makarova    ", "RUS",   0),
       ("Alize Cornet          ", "FRA",   4),
       ("Sorana Cirstea        ", "ROU",   6),
       ("Shuai Peng            ", "CHN",  -2),
       ("Sabine Lisicki        ", "GER",   8),
       ("Svetlana Kuznetsova   ", "RUS",  12),
       ("Varvara Lepchenko     ", "USA",  -3),
       ("Tamira Paszek         ", "AUT",   4),
       ("Lucie Safarova        ", "CZE",  -1),
       ("Mona Barthel          ", "GER",   4),
       ("Romina Oprandi        ", "SUI",   4),
       ("Klara Zakopalova      ", "CZE",  -9),
       ("Elena Vesnina         ", "RUS",   4),
       ("Venus Williams        ", "USA",  -3),
       ("Julia Goerges         ", "GER",  -8),
       ("Laura Robson          ", "GBR",   0),
       ("Urszula Radwanska     ", "POL",   2),
       ("Kristina Mladenovic   ", "FRA",   7),
       ("Bojana Jovanovski     ", "SRB",   7),
       ("Jie Zheng             ", "CHN",   2),
       ("Jamie Hampton         ", "USA",  12),
       ("Yanina Wickmayer      ", "BEL",  -2),
       ("Su-Wei Hsieh          ", "TPE",  -2),
       ("Francesca Schiavone   ", "ITA",   5),
       ("Kaia Kanepi           ", "EST", -20),
       ("Magdalena Rybarikova  ", "SVK",   5),
       ("Monica Niculescu      ", "ROU",   1),
       ("Ayumi Morita          ", "JPN",  -5),
       ("Lourdes Dominguez-Lino", "ESP",  -5),
       ("Stefanie Voegele      ", "SUI",   5),
       ("Yaroslava Shvedova    ", "KAZ", -21),
       ("Madison Keys          ", "USA",   5),
       ("Heather Watson        ", "GBR",  -6),
       ("Bethanie Mattek-Sands ", "USA",  12),
       ("Annika Beck           ", "GER",   6),
       ("Irina-Camelia Begu    ", "ROU",  -6),
       ("Simona Halep          ", "ROU",  -1),
       ("Kiki Bertens          ", "NED",  -4),
       ("Daniela Hantuchova    ", "SVK",   1),
       ("Johanna Larsson       ", "SWE",   5),
       ("Jana Cepelova         ", "SVK",   7),
       ("Christina McHale      ", "USA", -10),
       ("Maria Torro-Flor      ", "ESP",   7),
       ("Monica Puig           ", "PUR",  21),
       ("Tsvetana Pironkova    ", "BUL",  -7),
       ("Eugenie Bouchard      ", "CAN",  10),
       ("Chanelle Scheepers    ", "RSA",  -8),
       ("Mallory Burdette      ", "USA",  11),
       ("Garbine Muguruza      ", "ESP",   2),
       ("Marina Erakovic       ", "NZL",  21),
       ("Olga Govortsova       ", "BLR",  -9),
       ("Silvia Soler-Espinosa ", "ESP",  12),
       ("Karolina Pliskova     ", "CZE",  -1),
       ("Sofia Arvidsson       ", "SWE", -11),
       ("Lesya Tsurenko        ", "UKR",  -1),
       ("Mandy Minella         ", "LUX",  -1),
       ("Anna Tatishvili       ", "GEO",  -4),
       ("Anabel Garrigues      ", "ESP", -11),
       ("Melanie Oudin         ", "USA",  -2),
       ("Paula Ormaechea       ", "ARG",  37),
       ("Lara Arruabarrena     ", "ESP", -12),
       ("Elina Svitolina       ", "UKR",   7),
       ("Kimiko Date-Krumm     ", "JPN",  -1),
       ("Alexandra Cadantu     ", "ROU",   6),
       ("Olga Puchkova         ", "RUS",  -7),
       ("Misaki Doi            ", "JPN",  -5),
       ("Lauren Davis          ", "USA", -23),
       ("Donna Vekic           ", "CRO",  -1),
       ("Lucie Hradecka        ", "CZE",  -3),
       ("Yulia Putintseva      ", "KAZ",   7),
       ("Camila Giorgi         ", "ITA",  -8),
       ("Andrea Hlavackova     ", "CZE",  -4),
       ("Galina Voskoboeva     ", "KAZ",  29),
       ("Timea Babos           ", "HUN",   8),
       ("Estrella Cabeza       ", "ESP",   1),
       ("Pauline Parmentier    ", "FRA",   2),
       ("Vesna Dolonc          ", "SRB",  -5),
       ("Caroline Garcia       ", "FRA",  15),
       ("Polona Hercog         ", "SLO",  31) ) ;
     
     function Joueurs return T_Classement is
     begin
	return Les_Joueurs ;
     end Joueurs ;
     
     function Joueuses return T_Classement is
     begin
	return Les_Joueuses ;
     end Joueuses ;

end Tennis ;
   

